### ISSUE TITLE
Garbage Collection Job

### ISSUE THREAD

**Issue by BadBritishGamer** [New-Chance-RP/Suggested-Features#13]
<h2>What is your feature request?</h2>

Garbage collection job to be added, go to X place grab bags of rubbish move to next area. Could have patrol routes? A set waypoint or area that has to be followed as they would IRL once route is complete they get paid?

<h2>What are the benefits of your idea?</h2>

More interactive based stuff away from illegal activites, gives more passive entertainment.

<h2>Anything to support your idea?</h2>

N/A

**Comment by adsam56** [comment]
There is now a fully functioning garbage job
