### ISSUE TITLE
NPC's to not drop weapons

### ISSUE THREAD

**Issue by BadBritishGamer** [New-Chance-RP/Suggested-Features#15]
<h2>What is your feature request?</h2>

When an NPC is killed sometimes they carry weapons, these weapons should not be dropped when killed as this stops weapon farming.

<h2>What are the benefits of your idea?</h2>

Stops guns from being easily obtained
Potentially creates "path" for selling weapons for dirty cash

<h2>Anything to support your idea?</h2>

Go in game
Kill NPC with gun
Gun will drop

**Comment by ixhal** [comment]
Npcs should not longer drop weapons.
