### ISSUE TITLE
Bank UI Bug

### ISSUE THREAD

**Issue by HimWhoRobs** [New-Chance-RP/Suggested-Features#17]
<h2>What bug have you found?</h2>

The bank UI (the thumb Print screen) is not going away after using the bank. To reporduce this simple walk upto the bank and press E. the FlEEca screens comes up, however the camera is still controlled by your mouse so you are unable to click the thumb print leaving the UI in the middle of your screen.

<h2>What do you expect should happen?</h2>

When I press E at the bank my mouse should be toggled on so I can access the bank and get to my account allowing me to see my balance and transfer money.

**Comment by HimWhoRobs** [comment]
Replicating this bug seems to happen maybe 20% of the time however there is a smaller chance of a different UI coming through. Redmond should have dropped an image of this in discord pretty sure it is 2 separate bank UI clashing with each other.

**Comment by adsam56** [comment]
well take a look

**Comment by ixhal** [comment]
Should now be fixed, I'll leave the issue open just in case you find something else.

**Comment by ixhal** [comment]
Closing this for now if you notice anything strange with the banks please contact me on discord
