### ISSUE TITLE
Bank Card over Cash

### ISSUE THREAD

**Issue by HimWhoRobs** [New-Chance-RP/Suggested-Features#18]
<h2>What is your feature request?</h2>

Currently when trying to make big purchases like a car or anything from any store it requires cash to be carried on the player. I feel it to be an unnecessary risk carrying that much cash around.

<h2>What are the benefits of your idea?</h2>

Have big purchases (maybe all purchases) come straight from your bank account and not have cash be carried on players

<h2>Anything to support your idea?</h2>

Try buying any car and it will not allow you unless you have that amount of cash on the player

**Comment by ixhal** [comment]
You can now use bank balance to purchase cars, Let me know if there are any other things you need to buy with cash over 5k and I will change it
