### ISSUE TITLE
Bank screen displays wrong name

### ISSUE THREAD

**Issue by bloombydee** [New-Chance-RP/Suggested-Features#20]
<h2>What bug have you found?</h2>

Not a biggie but the bank overlay says 'welcome bloomb'

<h2>What do you expect should happen?</h2>

It should pull the name of the currently selected character

<h2>Anything to support your bug report?</h2>

Open the bank menu

**Comment by Senlarus** [comment]
Bank UI has been overhauled and it displays RP name now.
