### ISSUE TITLE
Removal of airplane blips

### ISSUE THREAD

**Issue by BadBritishGamer** [New-Chance-RP/Suggested-Features#25]
<h2>What bug have you found?</h2>

3 airplane blips visible on map, 2 at airport in the city and 1 at sandy airport. They have no use and need to be removed.

<h2>What do you expect should happen?</h2>

No Airplane blips visible at this time.

<h2>Anything to support your bug report?</h2>

N/A

**Comment by bloombydee** [comment]
this is part of the pilot job from the job center, this whole section needs to be commented out

**Comment by ixhal** [comment]
Removed.
