### ISSUE TITLE
Money Wash Removal

### ISSUE THREAD

**Issue by BadBritishGamer** [New-Chance-RP/Suggested-Features#27]
<h2>What bug have you found?</h2>
Money wash is currently viewable on the map via a blip, this money was needs removing and a better one implementing.

<h2>What do you expect should happen?</h2>

Money wash not visible and better

<h2>Anything to support your bug report?</h2>

N/A

**Comment by ixhal** [comment]
Removed, Working on a new one soon.

**Comment by ixhal** [comment]
New one is implemented still needs a little work but functional
