### ISSUE TITLE
Seat Belt/Spedometer

### ISSUE THREAD

**Issue by Monster-Duck** [New-Chance-RP/Suggested-Features#33]
I would love the addition of a Seatbelt and spedometer

Both of these features are found in real vehicles and help stop people from speeding, and add nice detail to a heavily driving based game.

This will help people know how fast they are going and stay safe on the road.

It has been on every city I've been in.

**Comment by bloombydee** [comment]
This should be fixed by the end of the day, the one we were using was part of the fuel script so when it was removed we lost the vehicle hud as well.

**Comment by ixhal** [comment]
New system now in place for this, Fuel still WiP.
