### ISSUE TITLE
NoClip Toggle

### ISSUE THREAD

**Issue by Monster-Duck** [New-Chance-RP/Suggested-Features#35]
<h2>Whenever I open my inventory Noclip is enabled</h2>

I went to open my inventory, and when I backed out of it I was in noclip. I then realized the key to enable noclip is the same as opening inventory. I have taken a clip of this, if it is wanted, but it should be easy to be recreated, and it would take me a while to upload.

I don't think I should have access to Noclip. I also think this would get extremely annoying for people who should have it trying to RP. Maybe move inventory/noclip key to stop this from happening, but regular players definitely shouldn't have noclip (maybe you left this to make finding bugs easier for us IDK, but it eventually needs to go)

I have a video, but I'll have to upload it to Youtube to share it, but I doubt its needed.

**Comment by ixhal** [comment]
Fixed the issue should not longer able to noclip.
