### ISSUE TITLE
Trunk/Glovebox

### ISSUE THREAD

**Issue by Monster-Duck** [New-Chance-RP/Suggested-Features#36]
<h2>I would like there to be a SEPARATE trunk and glovebox for vehicles.</h2>

The larger vehicles would have more trunk space. Motorcycles would only have a glovebox. For example: A Corquette would have the same glovebox as a Youga, but the youga would have an extremely larger trunk space. This would allow for a larger and more realistic storage.

<h2>What are the benefits of your idea?</h2>

I think this would make transport of any goods, legal or otherwise easier. It also would add realism to the city.

<h2>Anything to support your idea?</h2>

It is a nice feature, that might have been in the works before I said anything (sorry if it was)

**Comment by ixhal** [comment]
Is now available in-game press F9 to access the glovebox enjoy.
