### ISSUE TITLE
Bank robbery bug

### ISSUE THREAD

**Issue by lAmantel** [New-Chance-RP/Suggested-Features#38]
<h2>What bug have you found?</h2>

Myself and two other people were testing out the robbery at the LS Customs. Center City (Burton). We got to the second stage, and because the input key is left mouse button. It "knocked" me out, and left me stuck fetal position on the ground, ALIVE. 

<h2>What do you expect should happen?</h2>

We tried to recreate this with no avail, but to prevent this from happening again. I think maybe change the key used to select the input from Left Mouse Button to Enter like the previous step. 
Also maybe freeze your character whilst in this robbery action? If that's a possibility, Ultimately I think just changing the key to the same as the previous step will suffice.

<h2>Anything to support your bug report?</h2>

I didn't take a screen shot, but I do have the eyewitness of two people Discords: cNRR#5713 and N3rdymomma#1788

**Comment by ixhal** [comment]
Has been disabled for now will return in the future

**Comment by ixhal** [comment]
Has been disabled for now this is more of a future thing.
