### ISSUE TITLE
Phone as a physical Item

### ISSUE THREAD

**Issue by DerkDuece** [New-Chance-RP/Suggested-Features#39]
<h2>What is your feature request?</h2>

Basically the phone would be a item you would have to buy from the 24/7 that would allow you to use a phone. Would be a basic item check. 

<h2>What are the benefits of your idea?</h2>

Allows users to take others phone to ensure they cant call police when kidnapped or tweet when in jail and stuff like that. Also adds a nice element of realism. Also allows players to sell phones if they wanted to.

<h2>Anything to support your idea?</h2>

I feel it might be pretty simple to implement just a basic item check when players try and pull out their phone and if they dont have the item nothing happens.

**Comment by ixhal** [comment]
Phone is now a item, added to all "24/7" stores.
