### ISSUE TITLE
Drug Tests

### ISSUE THREAD

**Issue by N3rdymomma** [New-Chance-RP/Suggested-Features#4]
I would like to see at some point a drug test that PD/EMS have assess to through their jobs, but also maybe some home drug tests that civs could purchase through a pharmacy or the hospital. My idea was that seeing as different drugs stay in your system for different times that you can come up positive anywhere from 12 to 24 real time hours depending on the drug you ingest.

**Comment by BadBritishGamer** [comment]
Closed in reference for #6
