### ISSUE TITLE
Balance feedback passive income

### ISSUE THREAD

**Issue by Real50BMG** [New-Chance-RP/Suggested-Features#41]
<h2>What bug have you found?</h2>

Right now, as of in the testing server, the passive income is $150, which for 'realistic' amounts is quite a lot.

<h2>What do you expect should happen?</h2>

Passive income lowered to 10$. Collective income over all the players will be reduced heavily and makes the economy not inflate as hard as it will with 150$ being the passive income as of right now. Instead make 150$ per income be for a paid job like a police officer.

<h2>Anything to support your bug report?</h2>

This isn't necessarily an urgent thing, but more of a way to keep prices and incomes more realistic

**Comment by ixhal** [comment]
Lowered to 75 which is good for our eco
