### ISSUE TITLE
Dynamic drug locations

### ISSUE THREAD

**Issue by Real50BMG** [New-Chance-RP/Suggested-Features#46]
<h2>What is your feature request?</h2>

Somewhat dynamic druglocations:  maybe make multiple weedfarms, but only have 1 active at a given time, to simulate that farms actually get depleted instead of being harvested from 24/7. This could work for other drugs as well. Timebased? I.E only at night the meth pickup spot will be active

<h2>What are the benefits of your idea?</h2>

This makes certain spots not always being a hotspot for criminals, makes location camping harder, and is more realistic than having 1 spot being active at all times.

<h2>Anything to support your idea?</h2>

*DELETE THIS LINE Is there anything you can add which will help sell your idea, pictures, diagrams etc?*

**Comment by ixhal** [comment]
Not a bad Idea but people would spend too much time looking for the drugs, Our current system in not the end goal its just a taste for now.. we have good plans that will be implemented once we have time to work on one thing at a time.
