### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Real50BMG** [New-Chance-RP/Suggested-Features#48]
<h2>What is your feature request?</h2>

Have certain exotic and rare cars have a limited supply, as of now there is a limitless supply of any car thats at the dealers.

<h2>What are the benefits of your idea?</h2>

This will prevent from people driving the same exclusive cars as others, for example most Ferrari's don't get produced in massive quantities.

<h2>Anything to support your idea?</h2>

*DELETE THIS LINE Is there anything you can add which will help sell your idea, pictures, diagrams etc?*

**Comment by BadBritishGamer** [comment]
This is already planned,  import cars will be added in the future and have a whitelist role attached to them limiting how many cars can be bought. Or increasing price to meet demand etc.
