### ISSUE TITLE
Glovebox style storage system

### ISSUE THREAD

**Issue by Real50BMG** [New-Chance-RP/Suggested-Features#51]
<h2>What is your feature request?</h2>

A glovebox storage option in vehicles. The glovebox would be accessible from the inside, and the trunk would be accessible from the outside of the car.

<h2>What are the benefits of your idea?</h2>

Just another immersion type thing to have. Also makes trading items inside a car to another player more convenient. So you could do it through the glovebox 

<h2>Anything to support your idea?</h2>

*DELETE THIS LINE Is there anything you can add which will help sell your idea, pictures, diagrams etc?*

**Comment by ixhal** [comment]
See #36 enjoy, If you find out any bugs ect make a new issue cheers.
