### ISSUE TITLE
Upfront cost on drugs

### ISSUE THREAD

**Issue by Real50BMG** [New-Chance-RP/Suggested-Features#53]
<h2>What is your feature request?</h2>

Drugsystem having some kind of upfront cost. As of now there is not an upfront cost afaik. Not needing upfront money gives Danny’s too quick of an access to ultimately ‘end-game’ methods of making loads of money. Have the locations where they would pick for example weed cost money to enter. Not sure who would charge the person though. Could be either be another player controlled thing or an automated system. The location could be locked until a certain time of day, for example it only is accessible at night.

<h2>What are the benefits of your idea?</h2>

This makes the drugsystem less accessible to people that just started on the server. This would encourage them to find other ways of generating money (hopefully a more social way) like gambling against people or racing just to name a few ideas

<h2>Anything to support your idea?</h2>

*DELETE THIS LINE Is there anything you can add which will help sell your idea, pictures, diagrams etc?*

**Comment by ixhal** [comment]
see #46
