### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Real50BMG** [New-Chance-RP/Suggested-Features#55]
<h2>What is your feature request?</h2>

Some kind of system to share your exact location with someone, for example something similar to the 'ping' system used in NoPixel.

<h2>What are the benefits of your idea?</h2>

Nice feature to have, i have been in countless situations where such a system could have been extremely usefull to tell someone where i exactly was.

<h2>Anything to support your idea?</h2>

*DELETE THIS LINE Is there anything you can add which will help sell your idea, pictures, diagrams etc?*

**Comment by Senlarus** [comment]
This feature exists in the phone system. Thanks!
