### ISSUE TITLE
Separate characters

### ISSUE THREAD

**Issue by BadBritishGamer** [New-Chance-RP/Suggested-Features#7]
<h2>What is your feature request?</h2>

Multiple characters with separate bank accounts, separate phone numbers, separate everything for each character.

<h2>What are the benefits of your idea?</h2>

This will allow for better roleplay as characters won't be doing illegal/legal activities specifically for services. Cop wages stick on a legal character, they aren't then spent on gang based activities and it keeps the economy in a better shape.

Also stops people from switching between characters having same phone number making for awkward conversations etc.

<h2>Anything to support your idea?</h2>

N/A

**Comment by adsam56** [comment]
You can now have multiple characters
